#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: openjdk-8u91-jdk
        auth:
          username: nhuthuynhdocker
          password: "@bc123456"
    machine: true

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx256m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # Download and cache dependencies
      - restore_cache:
          keys:
          - eventuate-examples-java-spring-todo-list-{{ checksum "single-module/gradle.properties" }}
          # fallback to using the latest cache if no exact match is found
          - eventuate-examples-java-spring-todo-list-

      # - run: cd single-module && ./gradlew dependencies
      - run: cd multi-module && ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: eventuate-examples-java-spring-todo-list-{{ checksum "single-module/gradle.properties" }}

      # run tests!
      # - run: cd single-module && ./build-and-test-all-eventuate-local-mysql.sh
      # - run: cd single-module && ./build-and-test-all-eventuate-local-postgres-polling.sh
      # - run: cd single-module && ./build-and-test-all-eventuate-local-postgres-wal.sh
      # - run: cd multi-module && ./build-and-test-all-eventuate-local-mysql.sh
      # - run: cd multi-module && ./build-and-test-all-eventuate-local-postgres-wal.sh
      - run: java --version
      - run: cd multi-module && ./build-and-test-all-eventuate-local-postgres-polling.sh
