#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.282-browsers
        auth:
          username: nhuthuynhdocker
          password: "@bc123456"
    working_directory: ~/repo/multi-module/todo-servuce
    environment:
      # Customize the JVM maximum heap limit
      IMAGE_NAME: nhuthuynhdocker/first-build-success
      JVM_OPTS: -Xmx256m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master