#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.282-browsers
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: ~/repo/
    environment:
      # Customize the JVM maximum heap limit
      IMAGE_NAME: nhuthuynhdocker/first-build-success
      JVM_OPTS: -Xmx256m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      # build and push Docker image
      - run: ls -la
      - run: cd multi-module && ./gradlew assemble -P eventuateDriver=local
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest . && docker push $IMAGE_NAME:latest
#       - run: |
#           TAG=0.1.$CIRCLE_BUILD_NUM
#           docker build -t nhuthuynh-circle-ci/nhut-eventuate-todo-list:$TAG .
#           echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
#           docker push nhuthuynh-circle-ci/nhut-eventuate-todo-list:$TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master